import type { SocialLink, DesignProject } from '@/types/apps'

export const SOCIAL_LINKS: SocialLink[] = [
  { platform: 'twitter', url: '#', label: 'Twitter' },
  { platform: 'linkedin', url: '#', label: 'LinkedIn' },
  { platform: 'github', url: '#', label: 'GitHub' },
]

export const DESIGN_PROJECTS: DesignProject[] = [
  {
    id: 'fintech-dashboard',
    title: 'Fintech Dashboard',
    subtitle: 'the future of finance',
    description: 'Design system and React implementation for a financial technology platform.',
    longDescription: 'A comprehensive dashboard experience built for a fintech platform serving thousands of users. We developed a typography-first approach that prioritizes legibility and impact, creating a digital platform that behaves like a physical artifact—heavy, intentional, and permanent.',
    client: 'FinTech Corp',
    service: 'Product Design',
    focus: 'Dashboard Experience',
    category: 'Product Design',
    year: '2023',
    tags: ['Design System', 'React', 'Dashboard'],
    thumbnail: '',
    images: [],
    color: 'blue',
    bgColor: '#FF3010',
  },
  {
    id: 'mobile-banking',
    title: 'Mobile Banking',
    subtitle: 'banking reimagined',
    description: 'UX research and mobile design for a modern banking experience.',
    longDescription: 'Reimagining the mobile banking experience through extensive user research and iterative design. The result strips away the unnecessary to reveal the essential structure—clean, intuitive, and delightful to use daily.',
    client: 'NeoBank Inc',
    service: 'UX Research & Design',
    focus: 'Mobile Experience',
    category: 'UX Research',
    year: '2023',
    tags: ['UX Research', 'Mobile', 'iOS'],
    thumbnail: '',
    images: [],
    color: 'purple',
    bgColor: '#FF2A18',
  },
  {
    id: 'design-system-kit',
    title: 'Design System Kit',
    subtitle: 'components with soul',
    description: 'Open source component library with accessibility-first patterns.',
    longDescription: 'An open-source component library built from the ground up with accessibility as a core principle. Every component was designed to work beautifully across contexts while maintaining consistent behavior and visual language.',
    client: 'Open Source',
    service: 'Systems Design',
    focus: 'Component Architecture',
    category: 'Open Source',
    year: '2022',
    tags: ['Components', 'Accessibility', 'Open Source'],
    thumbnail: '',
    images: [],
    color: 'white',
    bgColor: '#FF4020',
  },
  {
    id: 'stealth-startup',
    title: 'Stealth Startup',
    subtitle: 'building the unknown',
    description: 'Product design consulting for an early-stage startup.',
    longDescription: 'Strategic product design consulting for an early-stage venture. Working from zero to one, we defined the visual language, interaction patterns, and design system that would scale with the product as it grew from concept to launch.',
    client: 'Confidential',
    service: 'Design Consulting',
    focus: 'Product Strategy',
    category: 'Consulting',
    year: '2024',
    tags: ['Product Design', 'Strategy', 'Consulting'],
    thumbnail: '',
    images: [],
    color: 'gray',
    bgColor: '#FF3518',
  },
]
